In [5]:
from array import array

# Definir el array
f = array('f', [1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reformatear el array en una matriz 3x3
matriz_3x3 = [[f[i*3 + j] for j in range(3)] for i in range(3)]

# Función para mostrar la matriz 3x3
def mostrar_matriz(matriz):
    for fila in matriz:
        print(fila)

# Función para buscar un elemento según su fila y columna en la matriz 3x3
def buscar_elemento(matriz, fila, columna):
    return matriz[fila - 1][columna - 1]

# Mostrar la matriz 3x3
print("Matriz 3x3:")
mostrar_matriz(matriz_3x3)

# Solicitar al usuario la fila y la columna
fila = int(input("\nIngrese el número de fila (1-3): "))
columna = int(input("Ingrese el número de columna (1-3): "))

# Verificar que las entradas estén dentro de los límites
if 1 <= fila <= 3 and 1 <= columna <= 3:
    # Buscar el elemento en la matriz 3x3
    elemento = buscar_elemento(matriz_3x3, fila, columna)
    print(f"\nEl elemento en la fila {fila} y columna {columna} es: {elemento}")
else:
    print("Fila o columna fuera de rango.")


Matriz 3x3:
[1.0, 2.0, 3.0]
[4.0, 5.0, 6.0]
[7.0, 8.0, 9.0]

Ingrese el número de fila (1-3): 1
Ingrese el número de columna (1-3): 1

El elemento en la fila 1 y columna 1 es: 1.0


In [16]:
from array import array

# Definir el array
f = array('f', [1, 2, 3, 4, 5, 6, 7, 8, 9])

# Mostrar la matriz 3x3 original
print("Matriz original:")
for i in range(0, len(f), 3):
    print("[" + " ".join(map(str, f[i:i+3])) + "]")

# 1. Multiplicar el primer renglón por 2
for i in range(3):
    f[i] *= 2

# 2. Intercambiar el primer y segundo renglón
f[0:3], f[3:6] = f[3:6], f[0:3]

# 3. Sumar el tercer renglón al segundo renglón multiplicado por un escalar, por ejemplo, 3
for i in range(3):
    f[i+3] += 3 * f[i+6]

# Mostrar la matriz resultante
print("\nMatriz resultante:")
for i in range(0, len(f), 3):
    print("[" + " ".join(map(str, f[i:i+3])) + "]")


Matriz original:
[1.0 2.0 3.0]
[4.0 5.0 6.0]
[7.0 8.0 9.0]

Matriz resultante:
[4.0 5.0 6.0]
[23.0 28.0 33.0]
[7.0 8.0 9.0]


In [19]:
import numpy as np
from array import array

# Definir el array
f = array('f',[1, 2, 3, 4, 5, 6, 7, 8, 9])

# Convertir a matriz de NumPy
matriz = np.array(f).reshape((3, 3))

# Mostrar la matriz original
print("Matriz original:")
print(matriz)

# 1. Multiplicar el primer renglón por 2
matriz[0] *= 2
print("\nMatriz después de multiplicar el primer renglón por 2:")
print(matriz)

# 2. Intercambiar el primer y segundo renglón
matriz[[0, 1]] = matriz[[1, 0]]
print("\nMatriz después de intercambiar el primer y segundo renglón:")
print(matriz)

# 3. Sumar el tercer renglón al segundo renglón multiplicado por un escalar, por ejemplo, 3
matriz[1] += 3 * matriz[2]
print("\nMatriz después de sumar el tercer renglón al segundo renglón multiplicado por 3:")
print(matriz)


Matriz original:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Matriz después de multiplicar el primer renglón por 2:
[[2. 4. 6.]
 [4. 5. 6.]
 [7. 8. 9.]]

Matriz después de intercambiar el primer y segundo renglón:
[[4. 5. 6.]
 [2. 4. 6.]
 [7. 8. 9.]]

Matriz después de sumar el tercer renglón al segundo renglón multiplicado por 3:
[[ 4.  5.  6.]
 [23. 28. 33.]
 [ 7.  8.  9.]]
